# Reusable workflow for drawing and committing an automated keymap diagram
# for ZMK config repos using https://github.com/caksoylar/keymap-drawer
name: Update Images
on: [push, pull_request, workflow_dispatch]

jobs:
  draw:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          submodules: recursive

      # - name: Install keymap-drawer (pypi)
      #   if: inputs.install_branch == ''
      #   run: python3 -m pip install keymap-drawer

      - name: Install keymap-drawer (git)
        run: python3 -m pip install "git+https://github.com/caksoylar/keymap-drawer.git"

      - name: Draw keymaps
        run: ./img/update

      - name: Commit updated images
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          file_pattern: "img/*.svg img/*.yaml"
          # So the previous commit is amended instead of creating a new one when desired
          # See:
          # - https://github.com/stefanzweifel/git-auto-commit-action#using---amend-and---no-edit-as-commit-options
          # - https://github.com/stefanzweifel/git-auto-commit-action/issues/159#issuecomment-845347950
          # - https://github.com/actions/checkout
          commit_message: "chore: updated keymap img"
