#!/bin/bash

set -e

LAYERS=(base lower raise adjust fun)

draw() {
  keymap -c ./img/config.yaml parse -z config/"$1".keymap >./img/"$1".yaml
  keymap -c ./img/config.yaml draw --select-layers "${LAYERS[@]}" -k boardsource/unicorne -l LAYOUT_split_3x5_3 ./img/"$1".yaml >./img/"$1".svg
}

draw corne
