#!/bin/sh

set -e

# LAYERS="Base Lower Raise Adjust Fun"

draw() {
	# keymap -c ./img/config.yaml parse -z config/"$1".keymap >./img/"$1".yaml
	# keymap -c ./img/config.yaml draw --select-layers "$LAYERS" -k "$2" ./img/"$1".yaml >./img/"$1".svg
  keymap -c ./img/config.yaml parse -z config/corne.keymap >./img/corne.yaml
  keymap -c ./img/config.yaml draw --select-layers Base Lower Raise Adjust Fun -k chocofi ./img/corne.yaml >./img/corne.svg
}

draw
# draw corne "chocofi"
